### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by geor-g** [stef/flask-tlsauth#1]
Hi @stef,

Thanks for your work on this. Because some time passed by since the last commit, I'm wondering if this code is suitable to use it in production. Do you use it regularly? If not: Do you know any alternatives? Looking forward to your feedback and opinion.

Thanks and all the best,
Georg

**Comment by stef** [comment]
sure its more like a framework around existing stuff in nginx and so on, i don't use it directly anymore, but variations of it in some places, yes.
