### ISSUE TITLE
Module fails to install as currently set up as currently released on PyPI

### ISSUE THREAD

**Issue by ZAdamMac** [stef/flask-tlsauth#2]
The app as it currently is posted to PyPI will not install - it fails on a syntax error during initial packaging. Full output of the attempt included below for reference.

patches@mir:~$ python3.6 -m pip install flask_tlsauth
Collecting flask_tlsauth
  Using cached https://files.pythonhosted.org/packages/d7/ec/9dbe881acebd59d24ab50ae07ac9a246d2b96db75552321119dc26070be1/flask_tlsauth-0.1.3.tar.gz
Collecting tlsauth (from flask_tlsauth)
  Using cached https://files.pythonhosted.org/packages/2c/34/430c1acc2fc810329979853f0c64841e20d078472fb9111f7068504aa179/tlsauth-0.4-1.tar.gz
Collecting Flask (from flask_tlsauth)
  Using cached https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl
Collecting M2Crypto (from tlsauth->flask_tlsauth)
  Using cached https://files.pythonhosted.org/packages/74/18/3beedd4ac48b52d1a4d12f2a8c5cf0ae342ce974859fba838cbbc1580249/M2Crypto-0.35.2.tar.gz
Collecting pyOpenSSL (from tlsauth->flask_tlsauth)
  Using cached https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl
Collecting pyasn1 (from tlsauth->flask_tlsauth)
  Using cached https://files.pythonhosted.org/packages/6a/6e/209351ec34b7d7807342e2bb6ff8a96eef1fd5dcac13bdbadf065c2bb55c/pyasn1-0.4.6-py2.py3-none-any.whl
Collecting pyspkac (from tlsauth->flask_tlsauth)
  Using cached https://files.pythonhosted.org/packages/c7/33/cf9a4142ad2078109c112c907150f3f5f352546545d6fabbdc14d0dd87c1/pyspkac-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vwqd93fl/pyspkac/setup.py", line 78, in <module>
        from pyspkac.version import VERSION
      File "/tmp/pip-build-vwqd93fl/pyspkac/pyspkac/__init__.py", line 2, in <module>
        from pyspkac.spkac   import SPKAC
      File "/tmp/pip-build-vwqd93fl/pyspkac/pyspkac/spkac.py", line 216
        except PyAsn1Error, e :
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vwqd93fl/pyspkac/

**Comment by stef** [comment]
looks like pyspkac is not python3 ready. also flask-tlsauth is not python3 ready so that will cause further problems. try python2 and all will be good ;)
